nv:
  enabled: true

competition:
  enable: false

rtp:
  enabled: true
  resistance_duration: 10 # seconds for resistence effect to last after teleport
  ranges:
    default:
      min: 0
      max: 10000

random:
  enabled: true

crusade:
  enabled: true