nv:
  enabled: true

competition:
  enabled: true
  item_name: "EGG"
  name: "Egg Collection Event"
  goal: 1000000
  collected: 0
  deposit_location:
    - x: 0
    - y: 0
    - z: 0
    - world: world
  

rtp:
  enabled: true
  resistance_duration: 10 # seconds for resistence effect to last after teleport
  allowed_worlds:
  - world
  ranges:
    default:
      min: 0
      max: 10000

random:
  enabled: false

crusade:
  enabled: true

hug:
  enabled: true
  heart_count: 15
  cooldown: 15

shulker_drops:
  enabled: true

ender_dragon_drops:
  enabled: true