api: []
name: PCNEssentials
main: net.peacefulcraft.rtp.PCNEssentials
version: 0.0.7
api-version: 1.21
softdepend: [CoreProtect]

commands:
    rtp:
      description: Random teleport every 1 minute
      usage: /<command> [range] [world] To RTP
    nv:
      description: Night Vision
      usage: /<command> To toggle night vision
    pcn-reload:
      description: Reload Plugin
      usage: /<command> To reload the plugin configuration file
    medals:
      description: Medal command for PCN competitions.
      usage: /<command> [place][usage][date]
    pumpkinmedal:
      description: Make a pumpkin medal
      usage: /<command> [title] [place] [description]
      permission: pcn.staff
    pickaxe:
      description: Pickaxe command for PCN competitions.
      usage: /<command> [place]
    boots:
      description: Boots command for PCN competitions
      usage: /<command> [place]
    crusade:
      description: Bombards the foe with a powerful crusade.
      usage: /<command> [player]
    pcnscore:
      description: Toggle scoreboard display for challenge
      usage: /<command> [on | off]
    randomDrops:
      description: Toggle random drops
      usage: /command [enable | disable]
    maketurkey:
      description: Sets all chickens to turkey event turkeys.
      usage: /<command>
    hug:
      description: Send a player your affections, within reason.
      usage: /<command> <username>
    pcncompetition:
      description: Commands for pcn competitions.
      usage: /<command>
    barrier:
      description: Creative give barrier
      usage: /<command>
      permission: pcn.barrier
