name: PCNEssentials
main: net.peacefulcraft.rtp.PCNEssentials
version: 0.0.3
api-version: 1.16
softdepend: [CoreProtect]

commands:
    rtp:
      description: Random teleport every 1 minute
      usage: /<command> To TRTP
    nv:
      description: Night Vision
      usage: /<command> To toggle night vision
    pcn-reload:
      description: Reload Plugin
      usage: /<command> To reload the plugin configuration file
    medals:
      description: Medal command for PCN competitions.
      usage: /<command> [place][usage][date]
    pickaxe:
      description: Pickaxe command for PCN competitions.
      usage: /<command> [place]
    boots:
      description: Boots command for PCN competitions
      usage: /<command> [place]
    crusade:
      description: Bombards the foe with a powerful crusade.
      usage: /<command> [player]
    pcnscore:
      description: Toggle scoreboard display for challenge
      usage: /<command> [on | off]
    randomDrops:
      description: Toggle random drops
      usage: /command [enable | disable]
    maketurkey:
      description: Sets all chickens to turkey event turkeys.
      usage: /<command>
    hug:
      description: Send a player your affections, within reason.
      usage: /<command> <username>
